In [178]:
import pandas as pd

In [179]:
data=pd.read_csv("영남호남_지역특산물.csv", encoding="utf-8-sig")

In [180]:
jeonbuk=data.query("도=='전북특별자치도'")
jeonbuk.head()

      상품명        도  시군구
0  부안해풍마늘  전북특별자치도  부안군
1    부안버섯  전북특별자치도  부안군
2  부안해풍양파  전북특별자치도  부안군
3     레드향  전북특별자치도  부안군
4      멜론  전북특별자치도  부안군

In [181]:
jeonnam=data.query("도=='전라남도'")
jeonnam.head()

     상품명     도  시군구
113   양파  전라남도  신안군
114  백년초  전라남도  신안군
115   마늘  전라남도  신안군
116   섬초  전라남도  신안군
117  무화과  전라남도  신안군

In [182]:
kyeongnam=data.query("도=='경상남도'")
kyeongnam.head()

      상품명     도  시군구
526  찰옥수수  경상남도  고성군
527  곱배인삼  경상남도  고성군
528    부추  경상남도  고성군
529   시금치  경상남도  고성군
530  파프리카  경상남도  고성군

In [183]:
kyeongbuk=data.query("도=='경상북도'")
kyeongbuk.head()

          상품명     도  시군구
318    영양 산나물  경상북도  영양군
319     영양 고추  경상북도  영양군
320        산초  경상북도  문경시
321  생명이(산나물)  경상북도  문경시
322       산양삼  경상북도  문경시

# 카테고리 나누기

카테고리 : 과일, 채소, 버섯, 곡류·잡곡, 축산물, 수산, 가공식품, 화훼, 노이즈(특산물로 분류가 안되는 장소같은 것)  
꿀, 치즈, 우유같은 경우는 축산물로 분류

# 1. 전북

In [184]:
print(jeonbuk["상품명"].tolist())

['부안해풍마늘', '부안버섯', '부안해풍양파', '레드향', '멜론', '오디', '부안줄포수박', '토마토', '부안딸기', '부안감자', '단풍미인찹쌀', '단풍미인배', '단풍미인방울토마토', '임실딸기', '임실토마토', '명품한우', '배', '복숭아', '콩', '고구마', '여름딸기', '배추,무', '토마토', '복숭아', '포도', '마늘', '고추', '사과', '바다향', '궁전꽃게장', '내고향시푸드', '아리울수산', '효송그린푸드', 'K-FOOD', '아리울현푸드', '영국빵집', '노시콩네 천연꿀농장', '웃담요구르트', '서해푸드 주식회사', '옥산한과', '더 미들래', '옹고집영농종합법인', '풍년보리원', '어울림', '중수비영농조합법인', '장미', '다래', '민물매운탕', '묵은지 닭볶음탕', '로컬푸드밥상', '순두부백반', '한우구이', '토마토', '배', '수박', '마늘', '양파', '대추', '딸기', '생강', '곶감', '딸기(삼례,고산,완창)', '표고', '단풍미인복분자주', '단풍미인토마토', '단풍미인씨없는 수박', '단풍미인한우', '단풍미인쌀', '볏단가리(친환경쌀)', '딸기', '토마토', '국화', '호박', '미나리', '포도', '배', '복숭아', '임실엿', '꿀', '씨없는동상곶감', '느타리버섯', '흑곶감', '고산대추', '경천대추', '동상 표고버섯', '봉동생강', '이서 신고배', '삼례수박', '비봉청정수박', '운주완창포도', '봉동왕포도', '고산마늘', '고산양파', '화산골자연한우', '화산양파', '회현면 흰찰쌀보리', '회현 농협 RPC', '옥구 농협 RPC', '생금들', '임실복숭아', '임실배', '임실한우', '임실치즈', '임실고추', '두릅', '오미자', '고추', '상추(쌈추)', '오디', '매실', '딸기', '복분자', '블루베리']

In [185]:
import re

# 1) 카테고리별 키워드(부분 문자열) 목록 ― 필요하면 추가·삭제·수정하세요
CATEGORY_KEYWORDS = {
    "과일": [
        "레드향", "멜론", "수박", "씨없는 수박", "딸기", "포도", "배", "복숭아",
        "사과", "대추", "다래", "오디", "오미자", "매실", "블루베리", "복분자"
    ],
    "채소": [
        "토마토", "방울토마토", "감자", "고구마", "배추", "무", "호박",
        "미나리", "두릅", "상추",
        "마늘", "양파", "고추", "생강"
    ],
    "버섯": [
        "버섯", "표고", "느타리"
    ],
    "곡류·잡곡": [
        "찹쌀", "쌀", "보리", "콩"
    ],
    "축산물": [
        "한우","꿀", "요구르트", "치즈"
    ],
    "수산": [
        "꽃게장"
    ],
    "가공식품": [
        "복분자주", "곶감", "엿", "한과", "식혜", "김치", "장아찌",
    ],
    "화훼": [
        "장미", "국화"
    ],
}

# 2) 노이즈(특산물이 아닌 시설·브랜드·조리식품 등) 키워드
NOISE_KEYWORDS = [
    "K-FOOD", "바다향", "시푸드", "수산", "푸드", "베이커리", "빵집", "농장",
    "요구르트", "영농", "RPC", "밥상", "백반", "구이", "매운탕", "묵은지", "더 미들래",
    "보리원", "어울림", "수비", "조합법인", "생금들"
]

# 3) 보조 함수: 괄호·공백 등 전처리
def _normalize(name: str) -> str:
    """
    ① ( ... ) 내용 제거
    ② 공백 제거
    ③ 대·소문자, 특수문자 차이가 없는 비교를 위해 lower 처리
    """
    name = re.sub(r"\(.*?\)", "", name)     # 괄호 제거
    name = re.sub(r"\s+", "", name)         # 모든 공백 제거
    return name.lower()

# 4) 최종 매핑 함수
def map_category(item: str) -> str:
    """
    '상품명'을 받아서 카테고리 문자열(또는 '노이즈') 반환
    """
    normalized = _normalize(item)

    # 4-1) 노이즈 먼저 거르기 ― 노이즈 키워드가 들어가면 바로 '노이즈'
    for noise_kw in NOISE_KEYWORDS:
        if noise_kw.lower().replace(" ", "") in normalized:
            return "노이즈"

    # 4-2) 각 카테고리 키워드 검사 (첫 매칭 카테고리 반환)
    for category, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            # 괄호·공백 제거 후 비교하기 위해 동일 전처리
            if _normalize(kw) in normalized:
                return category

    # 4-3) 어디에도 매칭되지 않으면 '노이즈'
    return "노이즈"

In [186]:

# 카테고리 매핑
jeonbuk["카테고리"] = jeonbuk["상품명"].apply(map_category)
jeonbuk.head()

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\924202458.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeonbuk["카테고리"] = jeonbuk["상품명"].apply(map_category)

      상품명        도  시군구 카테고리
0  부안해풍마늘  전북특별자치도  부안군   채소
1    부안버섯  전북특별자치도  부안군   버섯
2  부안해풍양파  전북특별자치도  부안군   채소
3     레드향  전북특별자치도  부안군   과일
4      멜론  전북특별자치도  부안군   과일

In [187]:
jeonbuk.isna().sum()

상품명     0
도       0
시군구     0
카테고리    0
dtype: int64

In [188]:
len(jeonbuk["상품명"])

113

In [189]:
len(jeonbuk["상품명"].drop_duplicates())

100

# 2. 전남

In [190]:
print(jeonnam["상품명"].tolist())

['양파', '백년초', '마늘', '섬초', '무화과', '석류', '고추', '포도', '배', '신안쌀', '진도 검정쌀', '홍주', '울금', '구기자', '잔디', '편백제품', '고로쇠', '새송이', '딸기', '토마토', '배', '포도', '단감&대봉', '사과', '브로콜리', '설도젓갈', '찰보리쌀', '태양초고추', '영광딸기', '간척지쌀', '대마할머니 막걸리', '천일염', '영광굴비', '전통감물염색', '천연황토염색', '왕골돗자리', '벌꿀, 로열제리', '꾸지뽕', '발아현미시리얼', '된장&청국장', '한과류', '잡곡', '고춧가루', '생도라지, 도라지가루', '어성초', '요구르트&치즈', '야생차', '표고버섯', '팽이버섯', '새송이버섯', '오이', '양파즙', '미니밤호박&단호박', '토마토', '오디', '딸기', '무화과&잼', '배', '사과', '함평천지 한우', '우렁색시미', '나비랑 여문쌀', '나비햇살미', '나비쌀', '모싯잎송편', '장흥버섯', '낙중장도', '기차마을 신동진쌀', '참다래', '단감', '복숭아', '배', '무화과', '영암도기', '영암어란', '월출전통메주', '금정토하젓', '달빛 무화과 쌀빵', '흑염소', '돼지고기', '녹색한우', '매력한우', '향토 지키미', '귀리다움 귀리', '연 관련 특산품', '무안갯벌 지주식 돌김', '무안고품질 쌀', '용문석', '전통염색', '삼베', '웅기', '고추', '오이', '감자', '쪽파', '방울토마토', '딸기', '사과', '참다래', '배', '웅치면올벼쌀', '건강미', '다향이숨쉬는쌀', '녹차미인보성쌀', '복분자', '삼백초', '어성초', '녹돈', '보성한우', '전어', '꼬막', '표고버섯', '느타리버섯', '녹차판매처', '녹차', '딸기', '깻잎', '벌꿀', '곡성한우', '곡성돌실나이', '깐토란', '고들빼기', '섬섬여수 옥수수', '아르미쌀', '청태전', '한우', '미나리', '조기햅쌀', '딸기묘', '매실', '순천오이', '단감', '대봉감', '달마지쌀', '겨울배추', '황토고구마', '해남김', '땅끝햇살', '단감', '송이버섯', '은어', '고로쇠약수', '배', '토종꿀', '산채류', '오이', '밤', '쌀', '토란대', '피토란', '토란파이만주', '황칠순액', '부각', '발아현미', '건나물', '처음처럼', '백세미', '곡성米', '흑찰옥수수', '토란', '거북선에 실린 쌀', '토마토', '유자차', '두릅', '여수동백화장품', '기능성잡곡', '금오도잎방풍', '거문도해풍쑥', '돌산갓김치', '황토고구마', '황토마늘', '황토양파', '김장무ㆍ배추ㆍ알타리무', '월출산토마토', '영암배', '풋고추', '영암월출수박', '황토고구마', '녹차한과', '녹차된장/고추장', '참외', '한라봉', '방울토마토', '멜론', '나주쌀', '나주배', '비파', '감자', '방울토마토', '삼지구엽초', '유자', '부지화', '포도', '마늘', '쌀', '블루베리', '밤', '포도', '곶감', '배', '사과', '딸기', '대봉', '매실', '멜론']

In [191]:
"""
상품명 → 카테고리 매핑 **완전 독립형 스크립트**  
(앞서 주신 베이스 구조를 그대로 유지하면서 - 두 번에 걸쳐 언급된
모든 특산물·가공식품·브랜드·노이즈 키워드를 ‘하나도 빠뜨리지 않고’ 포함)

✦ 사용 예
-----------------------------------------------------------------
import pandas as pd

df = pd.read_csv("your_data.csv")          # 반드시 `상품명` 컬럼이 있어야 함
df["카테고리"] = df["상품명"].apply(map_category)
-----------------------------------------------------------------
"""

import re

# ───────────────────────────────────────────────────────────────
# 1) 카테고리별 키워드
#    - 부분 문자열로 매칭합니다.
#    - 원하는 대로 추가·삭제·수정 가능
# ───────────────────────────────────────────────────────────────
CATEGORY_KEYWORDS = {
    # 과일류 ────────────────────────────────────────────────────
    "과일": [
        # 감귤·열대과·기타
        "레드향", "한라봉", "백년초", "비파", "참외", "멜론",
        # 수박
        "씨없는 수박", "단풍미인씨없는 수박",
        "부안줄포수박", "삼례수박", "비봉청정수박", "영암월출수박", "수박",
        # 딸기
        "영광딸기", "부안딸기", "임실딸기", "여름딸기", "딸기묘", "딸기",
        # 포도
        "운주완창포도", "봉동왕포도", "포도",
        # 배
        "단풍미인배", "이서 신고배", "임실배", "영암배", "나주배", "배",
        # 복숭아 외 과실
        "임실복숭아", "복숭아",
        "사과",
        "고산대추", "경천대추", "대추",
        "다래", "참다래",
        "오디",
        "복분자",
        "오미자",
        "매실",
        "블루베리",
        "무화과&잼", "달빛 무화과 쌀빵", "무화과",
        "석류",
        "단감&대봉", "대봉감", "대봉", "단감",
        "밤",
        "유자차", "유자","석류"
    ],

    # 채소류(근·엽·과채 + 양념채소) ────────────────────────────
    "채소": [
        # 토마토류
        "단풍미인토마토", "임실토마토", "월출산토마토",
        "방울토마토", "단풍미인방울토마토", "토마토",
        # 뿌리·줄기
        "부안감자", "감자",
        "황토고구마", "고구마",
        "배추,무", "겨울배추", "배추", "김장무", "알타리무", "무",
        "미니밤호박", "단호박", "호박",
        "토란파이만주", "토란대", "피토란", "토란",
        # 잎·줄기·기타
        "섬초", "브로콜리", "쪽파", "깻잎",
        "상추(쌈추)", "상추",
        "미나리",
        "두릅",
        "고들빼기",
        "옥수수", "흑찰옥수수", "섬섬여수 옥수수",
        "산채류", "금오도잎방풍", "거문도해풍쑥",
        # 양념채소·향신류
        "부안해풍마늘", "고산마늘", "황토마늘", "마늘",
        "부안해풍양파", "고산양파", "화산양파", "황토양파", "양파즙", "양파",
        "임실고추", "태양초고추", "고춧가루", "풋고추", "고추",
        "봉동생강", "생강","오이"
    ],

    # 버섯류 ────────────────────────────────────────────────────
    "버섯": [
        "부안버섯", "장흥버섯", "버섯",
        "새송이버섯", "새송이",
        "표고버섯", "동상 표고버섯", "표고",
        "느타리버섯", "느타리",
        "팽이버섯",
        "송이버섯",
    ],

    # 곡류·잡곡·쌀 ─────────────────────────────────────────────
    "곡류·잡곡": [
        # 기본
        "찹쌀", "쌀", "보리", "콩",
        # 각종 쌀 브랜드
        "신안쌀", "무안고품질 쌀", "간척지쌀", "나주쌀", "진도 검정쌀",
        "기차마을 신동진쌀", "웅치면올벼쌀",
        "나비랑 여문쌀", "나비햇살미", "나비쌀",
        "다향이숨쉬는쌀", "녹차미인보성쌀", "아르미쌀",
        "달마지쌀", "조기햅쌀", "거북선에 실린 쌀",
        "백세미", "곡성米",
        "발아현미시리얼", "발아현미",
        "회현면 흰찰쌀보리", "찰보리쌀", "보리",
        "귀리다움 귀리", "귀리",
        "건강미",
        "볏단가리(친환경쌀)",
        "기능성잡곡", "잡곡","구기자"
    ],

    # 축산물 및 양봉·유가공 ───────────────────────────────────
    "축산물": [
        "명품한우", "단풍미인한우", "화산골자연한우",
        "함평천지 한우", "녹색한우", "매력한우", "보성한우", "곡성한우",
        "한우구이", "한우",
        "돼지고기", "녹돈",
        "흑염소",
        "꿀", "벌꿀", "토종꿀", "로열제리",
        "요구르트&치즈", "요구르트", "치즈",
    ],

    # 수산·해조·젓갈 ──────────────────────────────────────────
    "수산": [
        "궁전꽃게장",
        "영광굴비",
        "전어",
        "꼬막",
        "무안갯벌 지주식 돌김",
        "해남김",
        "영암어란",
        "설도젓갈",
        "금정토하젓",
        "천일염","은어"
    ],

    # 가공식품·발효·주류·차 ─────────────────────────────────
    "가공식품": [
        "복분자주", "단풍미인복분자주",
        "곶감", "씨없는동상곶감", "흑곶감",
        "임실엿", "엿",
        "한과류", "옥산한과", "한과", "녹차한과",
        "식혜",
        "김치", "돌산갓김치",
        "장아찌",
        "된장&청국장", "된장", "청국장", "월출전통메주",
        "녹차된장/고추장", "고추장",
        "모싯잎송편",
        "막걸리", "대마할머니 막걸리",
        "소주", "홍주", "처음처럼",
        "달빛 무화과 쌀빵", "부각", "건나물",
        "발아현미시리얼",
        "유자차",
        "야생차", "청태전", "녹차",
        "황칠순액",
        "고로쇠", "고로쇠약수",
    ],

    # 화훼 ────────────────────────────────────────────────────
    "화훼": [
        "장미",
        "국화","부지화"
    ],
}

# ───────────────────────────────────────────────────────────────
# 2) 노이즈(시설·브랜드·공예품·서비스 등 특산물 아님) 키워드
# ───────────────────────────────────────────────────────────────
NOISE_KEYWORDS = [
    # 1차 답변 목록
    "K-FOOD", "바다향", "내고향시푸드", "아리울수산", "효송그린푸드",
    "아리울현푸드", "영국빵집", "노시콩네 천연꿀농장", "서해푸드 주식회사",
    "더 미들래", "옹고집영농종합법인", "풍년보리원", "어울림",
    "중수비영농조합법인", "민물매운탕", "묵은지 닭볶음탕", "로컬푸드밥상",
    "순두부백반", "회현 농협 RPC", "옥구 농협 RPC", "생금들",
    # 2차 답변 목록
    "잔디", "편백제품", "전통감물염색", "천연황토염색", "왕골돗자리",
    "전통염색", "용문석", "삼베", "웅기", "영암도기", "낙중장도",
    "녹차판매처", "곡성돌실나이", "여수동백화장품",
    # 공통 패턴(부분 문자열만 포함돼도 노이즈 처리)
    "판매처", "화장품", "도기", "공예", "석", "염색", "돗자리",
    "베이커리", "빵집", "농장", "시푸드", "수산", "푸드", "주식회사",
    "영농", "RPC", "밥상", "백반", "구이", "매운탕",
]

# ───────────────────────────────────────────────────────────────
# 3) 문자열 전처리 (비교 오차 최소화)
# ───────────────────────────────────────────────────────────────
def _normalize(text: str) -> str:
    """
    ① 괄호 ( ... ) 내용 제거
    ② 쉼표·&·/ → 공백
    ③ 모든 공백 제거
    ④ 소문자 변환
    """
    text = re.sub(r"\(.*?\)", "", str(text))      # 괄호 내용 제거
    text = re.sub(r"[,&/]", " ", text)            # 쉼표·&·/ → 공백
    text = re.sub(r"\s+", "", text)               # 공백 제거
    return text.lower()

# ───────────────────────────────────────────────────────────────
# 4) 최종 매핑 함수
# ───────────────────────────────────────────────────────────────
def map_category(item: str) -> str:
    """
    ▶ 입력 : 상품명(문자열)
    ▶ 출력 : 카테고리명 또는 '노이즈'
    """
    normalized = _normalize(item)

    # 4-1) 노이즈 키워드가 포함되면 바로 '노이즈'
    for noise_kw in NOISE_KEYWORDS:
        if _normalize(noise_kw) in normalized:
            return "노이즈"

    # 4-2) 카테고리별 키워드 검사 (첫 매칭된 카테고리 반환)
    for category, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if _normalize(kw) in normalized:
                return category

    # 4-3) 어디에도 속하지 않으면 '노이즈'
    return "노이즈"


# ───────────────────────────────────────────────────────────────
# 5) (옵션) 빠른 셀프 테스트
# ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    samples = [
        "부안해풍마늘", "단풍미인토마토", "영국빵집",
        "옥산한과", "영광굴비", "달빛 무화과 쌀빵",
        "여수동백화장품", "함평천지 한우", "황토고구마",
    ]
    for s in samples:
        print(f"{s:20} → {map_category(s)}")

부안해풍마늘               → 채소
단풍미인토마토              → 채소
영국빵집                 → 노이즈
옥산한과                 → 가공식품
영광굴비                 → 수산
달빛 무화과 쌀빵            → 과일
여수동백화장품              → 노이즈
함평천지 한우              → 축산물
황토고구마                → 채소

In [192]:
# 카테고리 매핑
jeonnam["카테고리"] = jeonnam["상품명"].apply(map_category)
jeonnam.head()

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\2458162238.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeonnam["카테고리"] = jeonnam["상품명"].apply(map_category)

     상품명     도  시군구 카테고리
113   양파  전라남도  신안군   채소
114  백년초  전라남도  신안군   과일
115   마늘  전라남도  신안군   채소
116   섬초  전라남도  신안군   채소
117  무화과  전라남도  신안군   과일

In [193]:
jeonnam.isna().sum()

상품명     0
도       0
시군구     0
카테고리    0
dtype: int64

In [194]:
len(jeonnam["상품명"])

205

In [195]:
len(jeonnam["상품명"].drop_duplicates())

168

# 3. 경북

In [196]:
print(kyeongbuk["상품명"].tolist())

['영양 산나물', '영양 고추', '산초', '생명이(산나물)', '산양삼', '오감만족', '오미로제', '호산춘', '오미자막걸리', '액상차', '작두콩,여주,자색돼지감자,야관문차', '국화차', '민들레김치', '민들레차', '메주, 된장, 간장', '한과', '양파, 양파즙', '문경약돌구운소금', '사과가공식품', '오미자김', '단무지', '문경새재 옛날찹쌀떡', '문경새재 오미자빵', '오미자 찰보리빵', '약돌돼지', '문경약돌한우', '산나물, 건나물', '미나리', '토마토', '문경곶감', '문경꿀', '느타리버섯', '새송이버섯', '표고버섯', '잡곡류', '새재의 아침쌀', '새재청결미', '문경약돌쌀', '희양산우렁쌀', '복숭아', '쌍샘배', '오미자', '문경사과', '안동곶감', '안동식혜', '안동국화차', '안동단호박', '안동딸기', '안동포', '안동고추', '안동쌀', '안동사과', '안동간고등어', '안동산약(마)', '안동포도', '안동한지', '하회탈', '안동소주', '안동참외', '안동한우', '짚공예', '포도(샤인머스캣)', '딸기', '고사리', '명이', '부지갱이', '미역취', '땅두릅', '두릅', '서덜취', '머위', '음나무', '섬초롱꽃', '단샘미', '일품쌀', '복숭아', '참외', '예천배', '양잠제품', '학가산메주', '고춧가루', '꽃돌', '남근목공방', '청송한지', '청송옹기', '국화차', '통밀빵', '야생화', '산나물김치', '엿기름', '칡즙', '전통장류', '상황버섯', '느타리버섯', '표고버섯', '상추', '오이와 호박', '포도', '꿀배', '고춧가루', '햇살듬뿍', '팽이버섯', '인진쑥', '부추', '딸기', '사과', '포도', '감자', '잡곡', '수박', '화훼', '표고버섯', '한약우', '송이', '고추', '사과', '가야그린포크 & 가야한우', '감자', '성산메론', '참고비(섬고사리)', '삼나물(눈개승마)', '두메부추', '오미자', '벌꿀', '노루궁뎅이 버섯', '표고버섯', '느타리버섯', '새송이버섯', '사과', '토마토', '참외', '감와인', '과육퓨레', '아이스홍시', '감잎차', '감식초', '반건시', '감말랭이', '쌀', '대추', '딸기', '느타리버섯', '팽이버섯', '노지고추', '한재미나리', '복숭아', '청도반시', '주왕산한우', '양봉꿀', '토종꿀', '야콘', '꽃송이버섯', '토마토', '파프리카', '토종대추', '세척고추', '청송사과', '산삼배양근', '벌꿀', '부각', '한과', '버섯', '술', '문어', '전통장류', '가지&애호박', '복숭아', '자두', '고구마', '참마', '생강', '포도', '콩', '계란', '쌀', '한우', '풍기인삼', '사과', '경주천년한우', '경주체리', '상주 오미자', '상주 벌꿀', '상주 복숭아', '상주 한우', '상주 오이', '상주 포도', '상주 사과', '상주 배', '상주 곶감', '상주 쌀', '김천자두', '김천포도', '고령 딸기', '참외', '우곡그린수박', '고령옥미', '마늘', '쌀', '복숭아', '자두', '사과', '양송이', '토마토', '예천 참기름', '금당꿀', '예천사과', '은풍준시 곶감', '예천잡곡']

In [197]:
"""
◎ 사용 방법 ─────────────────────────────────────────────
import pandas as pd

df = pd.read_csv("your_data.csv")          # 반드시 `상품명` 컬럼이 있어야 함
df["카테고리"] = df["상품명"].apply(map_category)
"""

import re

# ─────────────────────────────────────────────────────
# 1) 카테고리별 키워드 (부분 문자열 매칭)
#    ‣ 필요하면 자유롭게 추가·삭제·수정하세요
#    ‣ ‘우유·꿀·치즈·계란’ → 축산물에 포함
# ─────────────────────────────────────────────────────
CATEGORY_KEYWORDS = {
    # 과일류 ──────────────────────────────────────────
    "과일": [
        # 핵심 과수
        "사과", "배", "포도", "복숭아", "자두", "딸기",
        "참외", "수박", "멜론", "체리",
        # 감류·대추류
        "감", "반시", "곶감", "홍시",          # ※ 곶감·홍시는 가공식품에서도 잡음
        "대추", "토종대추",
        # 열대·감귤·기타
        "레드향", "한라봉", "비파", "매실", "유자",
        "오미자", "블루베리", "비파", "베리",
        "한라봉", "백년초","포도(샤인머스캣)","포도","상주 포도","김천포도"
    ],

    # 채소류 (양념채소·산나물 포함) ─────────────────────
    "채소": [
        # 일반 채소
        "토마토", "방울토마토", "파프리카",
        "감자", "고구마", "참마", "야콘",
        "배추", "무", "김장무", "알타리무",
        "호박", "애호박", "단호박",
        "오이", "가지",
        "미나리", "한재미나리",
        "두릅", "땅두릅",
        "부추", "두메부추",
        "상추", "부지갱이", "명이", "고사리",
        "미역취", "서덜취", "머위", "음나무",
        "산채", "산나물", "건나물", "삼나물", "섬초롱꽃", "참고비",
        # 양념·향신
        "마늘", "노지고추", "고추", "세척고추", "고춧가루",
        "양파", "황토양파", "양파즙",
        "생강",
        # 약용·기능성 채소를 여기 포함
        "산초", "인진쑥", "산삼배양근",
    ],

    # 버섯류 ──────────────────────────────────────────
    "버섯": [
        "버섯", "표고버섯", "표고", "느타리버섯", "느타리",
        "새송이버섯", "새송이", "팽이버섯", "양송이",
        "상황버섯", "송이", "꽃송이버섯", "노루궁뎅이 버섯",
    ],

    # 곡류·잡곡 ───────────────────────────────────────
    "곡류·잡곡": [
        "쌀", "찹쌀", "현미", "발아현미", "보리", "귀리",
        "잡곡", "곡성미", "곡성米", "곡류",
        "찰보리", "찰보리쌀",
        "신동진쌀", "약돌쌀", "청결미", "청결미",
        "우렁쌀", "청결미", "단샘미", "일품쌀",
        "옥미", "햅쌀",
        "참기름","콩" 
    ],

    # 축산물 (우유·꿀·치즈·계란 포함) ─────────────────
    "축산물": [
        "한우", "약돌한우", "주왕산한우", "녹색한우", "매력한우",
        "참한우", "상주 한우", "경주천년한우",
        "돼지고기", "약돌돼지", "포크",
        "계란", "알",  # 예: 유정란, 토종알 등
        "우유", "요구르트", "치즈",
        "꿀", "벌꿀", "양봉꿀", "토종꿀",
    ],

    # 수산물 ─────────────────────────────────────────
    "수산": [
        "꽃게장", "굴비", "간고등어", "문어", "김", "돌김",
        "소금", "구운소금", "천일염",
    ],

    # 가공식품 (발효·차·주류·떡·빵·조리품) ───────────
    "가공식품": [
        # 주류·음료
        "막걸리", "소주", "호산춘", "오미자막걸리", "안동소주",
        "감와인", "와인", "술",
        "차", "액상차", "국화차", "민들레차", "감잎차",
        "식혜",
        # 전통 장류·염장·발효식품
        "된장", "청국장", "간장", "고추장", "메주",
        "전통장류", "장류",
        "김치", "민들레김치", "산나물김치",
        "단무지", "장아찌",
        # 떡·빵·한과·과자
        "떡", "찹쌀떡", "한과", "빵", "오미자빵",
        "찰보리빵", "통밀빵",
        # 차가공/엑기스·농축액
        "칡즙", "엿기름",
        # 과일·채소 건조/가공품
        "곶감", "반건시", "감말랭이",
        "퓨레", "과육퓨레", "아이스홍시",
        "식초", "감식초",
        "퓨레",
        # 해조·부각
        "부각",
        # 잡곡·시리얼·시리얼바
        "발아현미시리얼",
        # 기타
        "소금", "구운소금",
        "오미자김", "오미로제", "오감만족",
        "사과가공식품",
    ],

    # 화훼 ────────────────────────────────────────────
    "화훼": [
        "화훼", "장미", "국화", "야생화",
    ],
}

# ─────────────────────────────────────────────────────
# 2) 노이즈 (특산물이 아닌 시설·공예·서비스·브랜드 등)
#    ※ ‘노이즈’가 우선순위!
# ─────────────────────────────────────────────────────
NOISE_KEYWORDS = [
    # 공예·공산품·관광 기념품
    "한지", "짚공예", "안동포", "안동한지", "청송한지",
    "청송옹기", "옹기", "하회탈", "목공방", "꽃돌", "양잠제품",
    # 업체·브랜드·기관·서비스
    "공방", "푸드", "베이커리", "빵집", "영농", "RPC", "주식회사",
    "판매처", "포", "우렁색시미", "햇살듬뿍",
    # 기타 잡음
    "K-FOOD", "더 미들래", "풍년보리원", "생금들",
]

# ─────────────────────────────────────────────────────
# 3) 전처리 함수
# ─────────────────────────────────────────────────────
def _normalize(text: str) -> str:
    """
    ① 괄호 ( ... ) 및 대괄호 [ ... ] 제거
    ② 쉼표·&·/ → 공백
    ③ 모든 공백 제거
    ④ 소문자로 변환
    """
    text = re.sub(r"[\(\[].*?[\)\]]", "", str(text))   # 괄호 내용 제거
    text = re.sub(r"[,&/]", " ", text)                 # 쉼표·&·/ → 공백
    text = re.sub(r"\s+", "", text)                    # 공백 제거
    return text.lower()

# ─────────────────────────────────────────────────────
# 4) 매핑 함수
# ─────────────────────────────────────────────────────
def map_category(item: str) -> str:
    """
    ▶ 입력 : 상품명(문자열)
    ▶ 출력 : 카테고리명 (과일·채소·…) 또는 '노이즈'
    """
    normalized = _normalize(item)

    # 4-1. 노이즈 먼저 검사
    for noise_kw in NOISE_KEYWORDS:
        if _normalize(noise_kw) in normalized:
            return "노이즈"

    # 4-2. 카테고리별 키워드 검사
    for category, kw_list in CATEGORY_KEYWORDS.items():
        for kw in kw_list:
            if _normalize(kw) in normalized:
                return category

    # 4-3. 어떤 항목에도 매칭되지 않으면 '노이즈'
    return "노이즈"

In [198]:
# 카테고리 매핑
kyeongbuk["카테고리"] = kyeongbuk["상품명"].apply(map_category)
kyeongbuk.head()

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\1091247514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kyeongbuk["카테고리"] = kyeongbuk["상품명"].apply(map_category)

          상품명     도  시군구 카테고리
318    영양 산나물  경상북도  영양군   채소
319     영양 고추  경상북도  영양군   채소
320        산초  경상북도  문경시   채소
321  생명이(산나물)  경상북도  문경시   채소
322       산양삼  경상북도  문경시  노이즈

In [199]:
kyeongbuk.isna().sum()

상품명     0
도       0
시군구     0
카테고리    0
dtype: int64

In [200]:
len(kyeongbuk["상품명"])

208

In [201]:
len(kyeongbuk["상품명"].drop_duplicates())

173

# 4. 경남

In [202]:
print(kyeongnam["상품명"].tolist())

['찰옥수수', '곱배인삼', '부추', '시금치', '파프리카', '화훼', '애호박', '취나물', '풋고추', '딸기', '버섯', '참다래', '방울토마토', '단감', '고성 쌀', '고성녹용', '고성돼지', '고성한우', '샤인머스켓', '성산사과', '함양농업가공사업소', '지리산마천농협', '인삼죽염', '삼민목장', '우리가', '지리산산골흑돼지', '장충동 B&F', '내수면 철갑상어', '밤', '공정육묘', '창녕체리', '감자', '창녕수박', '장목면 양파,유자', '붕장어', '새조개', '전어', '멸치', '쥐치', '바지락', '포도', '파프리카', '차나무', '새송이버섯', '느타리버섯', '수박', '참다래', '㈜석광아이티에스', '대원산업㈜', '㈜한국바이오케미칼', '㈜실키안', '금포영농조합법인', '민희영농조합법인', '㈜참진정', '진주시농협쌀조합공동사업법인', '송이식품', '문산머쉬영농조합법인', '햇살담은자연마을영농조합법인', '대호영농조합법인', '주흥미곡처리장', '㈜한일식품', '건웅식품㈜', '우엉마영농조합법인', '하봉정푸드', '반성전통한과', '㈜장생도라지', '싱싱단감농장', '밤', '녹차', '발효차', '허굴농차', '기능성소금선물세트', '황토소금', '벌꿀', '양계', '양돈', '한우', '복분자', '누에환, 동충하초, 뽕잎차', '녹차', '느타리버섯', '취나물', '양파', '마늘', '수박', '애플망고', '곶감', '남부면 고구마', '일운면 마늘, 상황버섯, 한라봉', '수양동 배추, 무', '상문동 무농약쌀', '곶감', '대나무숯', '밤', '새송이버섯', '상황버섯', '꽈리고추', '오이', '산머루', '옻', '새송이 버섯', '남해삼베', '만복당향', '한방향', '우렁쉥이', '홍합', '개조개', '굴', '바지락', '전복', '전어', '갈치', '붕장어', '멸치액젓', '멸치', '메주', '우리밀국수', '비자', '유자주', '고구마 쫀득이', '고구마 빼떼기죽', '미나리진액', '동백·유자오일', '옥수수', '마늘', '블루베리', '용과', '애플망고', '유자', '꿀', '계란', '돼지고기', '소고기', '상황버섯', '느타리버섯', '송이버섯', '감말랭이', '곶감', '절임배추', '두릅', '파프리카', '토마토', '여주', '딸기', '양파', '블루베리', '오미자', '복분자', '단감', '배', '사과', '밀가루', '잡곡', '쌀', '파프리카', '버섯', '안개초', '국화', '토마토', '파프리카', '멜론', '딸기', '참외', '풋고추', '수박', '천혜향', '복숭아', '블루베리', '키위', '단감', '국화', '은어', '카네이션', '표고버섯', '밤', '대추', '가지', '감자', '수박', '배', '포도', '얼음골 사과', '파프리카', '홍고추', '꽈리고추', '청양고추', '밀양 들깻잎', '얼음골쌀', '흙으로빚은쌀', '밀양아리랑쌀', '동부면 표고버섯, 알로에', '거제면 파프리카, 한라봉, 알로에, 토마토, 파인애플', '둔덕면 포도, 축산', '사등면 유자, 비파, 토마토, 느타리버섯', '연초면 상황버섯, 들깨, 유자', '하청면 맹종죽(죽순), 풋고추, 유자, 치자', '딸기', '밤', '곶감', '단감', '배', '사과', '고구마', '산청친환경쌀', '파프리카', '양상추', '참다래', '토마토', '수박', '딸기', '단감', '대봉감', '배', '산양삼', '남해유정란', '보물섬남해한우', '남해재래 시금치', '호박차,호박찜', '참다래', '땅두릅', '박나물', '청정쌀', '고사리', '치자', '유자청', '유자', '알로에', '마늘', '돼지고기 부분육', '창녕한우', '우포늪복숭아', '파프리카', '토마토', '풋고추', '화왕산미나리', '창녕오이', '창녕단감', '창녕고추', '창녕마늘', '창녕양파', '참외', '포도', '연근', '단감', '복숭아', '방울토마토', '메론', '오이', '수박', '매실', '딸기', '토마토', '배', '단감', '호접란', '우엉', '마', '복숭아', '매실', '배', '단감', '진주고추', '깻잎', '토마토', '수박', '메론', '가지', '파프리카', '호박', '피망', '딸기', '사과', '파프리카', '미나리', '도자기', '우렁이쌀', '합천황토한우', '황매산 블루베리', '표고버섯', '친환경 고추', '유기농 토마토', '딸기', '친환경 쌀', '고사리', '두릅', '꿀', '덕곡생생마늘', '합천토종흑돼지', '곰취', '브로콜리', '수박', '호박', '양파', '전통 장류', '꿈꾸는 달걀', '메론', '배', '쥬키니', '방울토마토', '양떡메(양파즙, 떡가래, 메주)', '산그리메(국화차)', '산그리메(감잎차)', '산그리메(뽕잎차)', '합천 육묘장', '봉산건강원', '매실', '고추', '유자청', '참다래', '시금치', '땅두릅', '파프리카', '밀감', '딸기', '고구마줄기', '통영풍난', '고구마', '산딸기', '키위', '매실', '포도', '복숭아', '단감', '파프리카', '부추', '가지', '토마토', '참외', '딸기', '서양란', '금어초', '숙근안개초', '거베라', '카네이션', '국화', '장미&장군차', '한천', '양란', '딸기', '단감', '창녕 송이버섯']

In [203]:
"""
◎ 사용 방법 ─────────────────────────────────────────────
import pandas as pd

df = pd.read_csv("your_data.csv")          # 반드시 `상품명` 컬럼이 있어야 함
df["카테고리"] = df["상품명"].apply(map_category)
"""

import re

# ─────────────────────────────────────────────────────
# 1) 카테고리별 키워드 (부분 문자열 매칭)
#    ‣ 필요하면 자유롭게 추가·삭제·수정하세요
#    ‣ ‘우유·꿀·치즈·계란’ → 축산물에 포함
# ─────────────────────────────────────────────────────
CATEGORY_KEYWORDS = {
    # 과일류 ──────────────────────────────────────────
    "과일": [
        # 핵심 과수
        "사과", "배", "포도", "샤인머스켓", "복숭아", "자두", "딸기",
        "체리", "참외", "수박", "멜론", "키위",
        # 감·대추·베리류
        "감", "반건시", "감말랭이", "곶감", "대봉감", "단감",
        "대추", "토종대추", "산머루", "블루베리", "복분자",
        # 열대·감귤·기타
        "레드향", "한라봉", "천혜향", "애플망고", "비파", "유자", "매실",
        "오미자", "용과", "베리",
        # 견과
        "밤",
    ],

    # 채소류 (양념채소·산나물 포함) ─────────────────────
    "채소": [
        # 일반 채소
        "토마토", "방울토마토", "파프리카", "피망",
        "감자", "고구마", "고구마줄기", "마", "참마",
        "배추", "무", "절임배추",
        "호박", "애호박", "단호박", "쥬키니",
        "오이", "가지",
        "양파", "황토양파", "양파즙",
        "마늘",
        "연근", "우엉",
        "브로콜리",
        "시금치", "남해유정란? no",  # keep s pin
        "미나리", "화왕산미나리",
        "두릅", "땅두릅",
        "부추", "두메부추",
        "깻잎", "들깨",
        "고추", "풋고추", "꽈리고추", "홍고추", "청양고추", "노지고추", "세척고추",
        "고춧가루",
        "곰취", "취나물", "박나물",
        "고사리",
        "삼나물", "산나물", "건나물", "산채", "산채류", "미역취", "서덜취",
        "음나무", "부지갱이",
        "차나무", "양상추", "치자","메론","알로에"                 # 녹차·발효차 원료
    ],


    "버섯": [
        "버섯", "표고버섯", "표고", "느타리버섯", "느타리",
        "새송이버섯", "새송이", "팽이버섯",
        "양송이버섯", "양송이",
        "송이버섯", "송이",
        "상황버섯",
        "꽃송이버섯",
        "노루궁뎅이버섯", "노루궁뎅이 버섯",
    ],

    # 곡류·잡곡 ───────────────────────────────────────
    "곡류·잡곡": [
        "쌀", "찹쌀", "현미", "발아현미", "보리", "귀리", "옥수수", "찰옥수수",
        "잡곡", "곡성米", "곡성미", "곡류",
        "햇쌀", "햅쌀",
        "무농약쌀", "친환경쌀", "청결미",
        "우렁쌀", "우렁이쌀",
        "약돌쌀", "새재의 아침쌀", "새재청결미",
        "희양산우렁쌀",
        "단샘미", "일품쌀", "얼음골쌀", "흙으로빚은쌀", "밀양아리랑쌀",
        "고성 쌀", "창녕옥미", "상문동 무농약쌀",
        "밀가루", "우리밀국수",
    ],

    # 축산물 (우유·꿀·치즈·계란 포함) ─────────────────
    "축산물": [
        "한우", "보물섬남해한우", "창녕한우", "합천황토한우",
        "경주천년한우", "상주 한우", "주왕산한우", "고성한우", "문경약돌한우",
        "돼지고기", "약돌돼지", "고성돼지", "흑돼지", "포크", "돼지고기 부분육",
        "양돈", "양계",
        "계란", "유정란", "꿈꾸는 달걀",
        "우유", "목장", "요구르트", "치즈",
        "꿀", "벌꿀", "양봉꿀", "토종꿀", "금당꿀",
        "녹용", "고성녹용","양란"
    ],

    # 수산물 ─────────────────────────────────────────
    "수산": [
        "철갑상어",
        "붕장어", "전어", "갈치", "쥐치", "멸치", "멸치액젓",
        "새조개", "바지락", "개조개", "홍합", "굴", "전복", "우렁쉥이",
        "김", "돌김",
        "소금", "황토소금", "기능성소금", "구운소금","은어"
    ],

    # 가공식품 (발효·차·주류·떡·빵·조리품) ───────────
    "가공식품": [
        # 장류·발효
        "메주", "된장", "간장", "청국장", "고추장", "전통장류",
        "장류", "인삼죽염",
        # 주류·음료
        "막걸리", "오미자막걸리", "호산춘", "안동소주", "유자주", "와인",
        "감와인", "술",
        "차", "발효차", "액상차", "국화차", "안동국화차", "민들레차",
        "감잎차", "뽕잎차", "야관문차",
        # 떡·빵·한과
        "한과", "반성전통한과", "문경새재 옛날찹쌀떡", "떡",
        "빵", "통밀빵", "오미자빵", "찰보리빵",
        # 과일·채소 가공품
        "곶감", "감말랭이", "반건시",
        "오미자 찰보리빵", "오미로제", "오감만족", "사과가공식품",
        "고구마 쫀득이", "고구마 빼떼기죽",
        "퓨레", "과육퓨레", "아이스홍시",
        "식초", "감식초",
        # 차·진액·엑기스
        "미나리진액", "유자청",
        # 해조·부각
        "부각",
        # 곡물가공
        "발아현미시리얼",
    ],

    # 화훼 ────────────────────────────────────────────
    "화훼": [
        "화훼", "서양란", "호접란", "안개초", "숙근안개초",
        "카네이션", "국화", "장미", "금어초", "거베라",
    ],
}

# ─────────────────────────────────────────────────────
# 2) 노이즈 (특산물이 아닌 시설·공예·서비스·브랜드 등)
#    ※ ‘노이즈’가 우선순위!
# ─────────────────────────────────────────────────────
NOISE_KEYWORDS = [
    # 공예·가공 아닌 특산물
    "한지", "짚공예", "도자기", "남해삼베", "청송옹기", "옹기",
    "하회탈", "목공방", "비자", "만복당향", "한방향",
    # 기업·법인·기관·사업소·농협
    "농협", "영농조합법인", "조합공동사업법인", "조합법인", "영농",
    "사업소", "미곡처리장", "식품", "푸드", "주식회사",
    # 브랜드·시설
    "공정육묘", "육묘장", "농장", "목장", "브랜드", "플라워", "공원",
    # 기타
    "K-FOOD", "B&F", "ITS", "아이티에스", "실키안",
]

# ─────────────────────────────────────────────────────
# 3) 전처리 함수
# ─────────────────────────────────────────────────────
def _normalize(text: str) -> str:
    """
    ① 괄호 ( ... ) 및 대괄호 [ ... ] 제거
    ② 쉼표·&·/ → 공백
    ③ 모든 공백 제거
    ④ 소문자로 변환
    """
    text = re.sub(r"[\(\[].*?[\)\]]", "", str(text))   # 괄호 내용 제거
    text = re.sub(r"[,&/]", " ", text)                 # 쉼표·&·/ → 공백
    text = re.sub(r"\s+", "", text)                    # 공백 제거
    return text.lower()

# ─────────────────────────────────────────────────────
# 4) 매핑 함수
# ─────────────────────────────────────────────────────
def map_category(item: str) -> str:

    normalized = _normalize(item)

    # 4-1. 노이즈 먼저 검사
    for noise_kw in NOISE_KEYWORDS:
        if _normalize(noise_kw) in normalized:
            return "노이즈"

    # 4-2. 카테고리별 키워드 검사
    for category, kw_list in CATEGORY_KEYWORDS.items():
        for kw in kw_list:
            if _normalize(kw) in normalized:
                return category

    # 4-3. 어떤 항목에도 매칭되지 않으면 '노이즈'
    return "노이즈"

In [204]:
# ── 빠른 자체 진단
for sample in ["찰옥수수", "파프리카"]:
    print(sample, "→", map_category(sample))

찰옥수수 → 곡류·잡곡
파프리카 → 채소

In [205]:
# 카테고리 매핑
kyeongnam["카테고리"] = kyeongnam["상품명"].apply(map_category)
kyeongnam.head()

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\1461246413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kyeongnam["카테고리"] = kyeongnam["상품명"].apply(map_category)

      상품명     도  시군구   카테고리
526  찰옥수수  경상남도  고성군  곡류·잡곡
527  곱배인삼  경상남도  고성군     과일
528    부추  경상남도  고성군     채소
529   시금치  경상남도  고성군     채소
530  파프리카  경상남도  고성군     채소

In [206]:
kyeongnam.isna().sum()

상품명     0
도       0
시군구     0
카테고리    0
dtype: int64

In [207]:
len(kyeongnam["상품명"])

341

In [208]:
len(kyeongnam["상품명"].drop_duplicates())

223

# 데이터 최종 - 중복없애기

In [209]:
jeonbuk.drop_duplicates(subset=["상품명"], keep="first", inplace=True)
jeonbuk.reset_index(drop=True, inplace=True)
jeonbuk.shape

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\888392717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeonbuk.drop_duplicates(subset=["상품명"], keep="first", inplace=True)

(100, 4)

In [210]:
jeonnam.drop_duplicates(subset=["상품명"], keep="first", inplace=True)
jeonnam.reset_index(drop=True, inplace=True)
jeonnam.shape

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\2305146028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeonnam.drop_duplicates(subset=["상품명"], keep="first", inplace=True)

(168, 4)

In [211]:
kyeongbuk.drop_duplicates(subset=["상품명"], keep="first", inplace=True)
kyeongbuk.reset_index(drop=True, inplace=True)
kyeongbuk.shape

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\768834473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kyeongbuk.drop_duplicates(subset=["상품명"], keep="first", inplace=True)

(173, 4)

In [212]:
kyeongnam.drop_duplicates(subset=["상품명"], keep="first", inplace=True)
kyeongnam.reset_index(drop=True, inplace=True)
kyeongnam.shape

C:\Users\swoo6\AppData\Local\Temp\ipykernel_38220\2055767718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kyeongnam.drop_duplicates(subset=["상품명"], keep="first", inplace=True)

(223, 4)

## 노이즈 제거하기

In [213]:
jeonbuk=jeonbuk.query("카테고리 != '노이즈'")
jeonnam=jeonnam.query("카테고리 != '노이즈'")
kyeongbuk=kyeongbuk.query("카테고리 != '노이즈'")
kyeongnam=kyeongnam.query("카테고리 != '노이즈'")

## 데이터 저장하기

In [214]:
jeonbuk.to_csv("전라북도_특산물.csv", index=False, encoding="utf-8-sig")
jeonnam.to_csv("전라남도_특산물.csv", index=False, encoding="utf-8-sig")
kyeongbuk.to_csv("경상북도_특산물.csv", index=False, encoding="utf-8-sig")
kyeongnam.to_csv("경상남도_특산물.csv", index=False, encoding="utf-8-sig")